#!/bin/bash
## D.C. Noye 2016
### Latest version of script found here: 
#### https://github.com/dcnoye/dmotd

PROCCOUNT=`ps -Afl | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 5`
DIR=`dirname "$0"`
if [[ $GROUPZ == "$USER sudo" ]]; then
	USERGROUP="Administrator"
elif [[ $USER = "root" ]]; then
	USERGROUP="Root"
elif [[ $USER = "$USER" ]]; then
	USERGROUP="Regular User"
else
	USERGROUP="$GROUPZ"
fi
echo -e "\033[1;32m 
\033[0;35m +++++++++++++++++: \033[0;37mSystem Data\033[0;35m :+++++++++++++++++++
\033[0;35m +           \033[0;37mTime \033[0;35m= \033[1;32m`date`
\033[0;35m +       \033[0;37mHostname \033[0;35m= \033[1;32m`hostname`
\033[0;35m +   \033[0;37mIPv4 Address \033[0;35m= \033[1;32m`/sbin/ip a | grep "inet\ " | awk {'print $2'}|tail -n1`
\033[0;35m +   \033[0;37mIPv4 Address \033[0;35m= \033[1;32m`curl ifconfig.io -s`
\033[0;35m +   \033[0;37mIPv6 Address \033[0;35m= \033[1;32m`/sbin/ip a | grep -m 1 "inet6\ " | awk {'print $2'}`         
\033[0;35m +         \033[0;37mKernel \033[0;35m= \033[1;32m`uname -r`
\033[0;35m +         \033[0;37mDistro \033[0;35m= \033[1;32m`cat /etc/*release |  cut -d "=" -f 2- | head -n1| sed 's/"//g'`
\033[0;35m +         \033[0;37mUptime \033[0;35m= \033[1;32m`uptime | sed 's/.*up ([^,]*), .*/1/'`
\033[0;35m +            \033[0;37mCPU \033[0;35m= \033[1;32m`cat /proc/cpuinfo | grep "model name" | cut -d ' ' -f3- | awk {'print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10'} | head -1`
\033[0;35m +         \033[0;37mMemory \033[0;35m= \033[1;32m`free -t -m | grep "Mem" | awk {'print $4'}`MB Available, `free -t -m | grep "Mem" | awk {'print $3'}`MB Used, `free -t -m | grep "Mem" | awk {'print $2'}`MB Total
\033[0;35m +      \033[0;37mHDD Usage \033[0;35m= \033[1;32m`df -hT | grep "/home" | awk {'print $4'}` Available, `df -hT | grep "/home" | awk {'print $5'}` Used, `df -hT | grep "/home" | awk {'print $2'}` Total 
\033[0;35m +++++++++++++++++: \033[0;37mOpenVZ\033[0;35m :++++++++++++++++++++++++
\033[0;35m
\033[0;35m`/usr/sbin/vzlist -a -octid,numproc,status,ip,hostname,laverage,cpus,cpuunits,diskspace,diskspace.s,onboot,disabled,description`
\033[0;35m
\033[0;35m
"
